#!/bin/env node
'use strict';

var connection_string = 'mongodb://' +
    process.env.OPENSHIFT_MONGODB_DB_USERNAME + ":" +
    process.env.OPENSHIFT_MONGODB_DB_PASSWORD + "@" +
    process.env.OPENSHIFT_MONGODB_DB_HOST + ':' +
    process.env.OPENSHIFT_MONGODB_DB_PORT;

var MongoClient = require('mongodb').MongoClient;

MongoClient.connect(connection_string, function(err, mongoclient) {
    var result = mongoclient.executeDbAdminCommand({ setParameter : 1, textSearchEnabled : true } );

    result.then(function(result) {
        console.log(result);

        mongoclient.close();
    });
});