#!/bin/env node
'use strict';

var connection_string = 'mongodb://' +
    process.env.OPENSHIFT_MONGODB_DB_USERNAME + ":" +
    process.env.OPENSHIFT_MONGODB_DB_PASSWORD + "@" +
    process.env.OPENSHIFT_MONGODB_DB_HOST + ':' +
    process.env.OPENSHIFT_MONGODB_DB_PORT;

var MongoClient = require('mongodb').MongoClient;
var pagarme = require('pagarme-nodejs')('ak_test_KwMAwfL6kGrt3kO9mgNC3qWnvdYe0C');

MongoClient.connect(connection_string, function (err, mongoclient) {
    var db = mongoclient.db('grupo');

    db
        .collection('carrinhos')
        .find(
        {
            status: {
                $in: ['novo']
            },
            token: {
                $ne: null
            }
        },
        function (err, rows) {
            if (err) {
                return console.error(err);
            }

            rows.forEach(function (row) {
                pagarme.transactions.findById(row.token, function(err, transaction) {
                    var status = 'estornado';

                    if (!err) {
                        if (transaction.status == 'paid') {
                            status = 'pago';
                        }

                        if (transaction.status == 'waiting_payment') {
                            status = 'novo';
                        }
                    }

                    var carrinho = require(__dirname + '/../../../src/models/carrinho');
                        carrinho.findByIdAndUpdate(row._id, {status: status});

                    mongoclient.close();
                });
            });
        }
    );
});